import { useState } from "react";
import { type NextPage } from "next";

import Head from "next/head";
import WebForm from "../components/WebForm";
import ThankYou from "../components/ThankYou";
import ErrorComponent from "../components/ErrorComponent";
import { Chat } from "~/components/Chat";
import DropZone from "~/components/ui/dropZone";
import useUploadPdf from "~/hooks/useUploadPdf";
import { nanoid } from "ai";

export type WithResponseProps = {
  setResponse: React.Dispatch<React.SetStateAction<boolean | null>>;
};

const Home: NextPage = () => {
  // null -> form has not been submitted
  // true -> form has been submitted successfully
  // false -> form has been submitted unsuccessfully
  const [response, setResponse] = useState<boolean | null>(null);

  const [sessionId, setSessionId] = useState<string>(`session-id-${nanoid()}`);
  const { onUpload, isUploading } = useUploadPdf(sessionId);
  const [files, setFiles] = useState<File[]>([]);

  const onFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files === null) return;
    const filesArray = Array.from(files);
    setFiles(filesArray);
    await onUpload(filesArray);
  };

  return (
    <>
      <Head>
        <title>Interest Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <DropZone
        onFileChange={onFileChange}
        files={files}
        isUploading={isUploading}
      /> */}
      <main className="flex min-h-screen flex-col items-center justify-center bg-background">
        {response === null ? (
          <WebForm setResponse={setResponse} />
        ) : response ? (
          <ThankYou />
        ) : (
          <ErrorComponent setResponse={setResponse} />
        )}
        
      <div className="flex flex-1 py-4">
        <div className="w-full">
          <Chat sessionId={sessionId} isUploading={isUploading} />
        </div>
      </div>
      </main>
    </>
  );
};

export default Home;
